from __future__ import annotations

from typing import Generic, TypeVar, Type, List, Optional, Dict, Any
from sqlalchemy.orm import Session
from sqlalchemy.exc import NoResultFound

from .abstract import AbstractRepository

T = TypeVar('T')


class SQLAlchemyRepository(AbstractRepository[T], Generic[T]):
    """Generic repository that operates on a SQLAlchemy model class.

    The repository receives a Session instance (injected) and a model class.
    It does not create or manage the session lifecycle (caller is responsible).
    """

    def __init__(self, session: Session, model_class: Type[T]):
        self.session = session
        self.model_class = model_class

    def add(self, obj: T) -> T:
        self.session.add(obj)
        self.session.commit()
        # Refresh to populate defaults / autogenerated fields
        self.session.refresh(obj)
        return obj

    def get(self, id: int) -> Optional[T]:
        try:
            return self.session.query(self.model_class).get(id)
        except NoResultFound:
            return None

    def list(self, **filters: Any) -> List[T]:
        query = self.session.query(self.model_class)
        if filters:
            query = query.filter_by(**filters)
        return query.all()

    def delete(self, id: int) -> None:
        obj = self.get(id)
        if obj is None:
            return
        self.session.delete(obj)
        self.session.commit()
